addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.4.7")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt" % "2.5.4")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix" % "0.14.3")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"  % "0.6.3")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly" % "2.3.0")
